"""Fix inventory

Revision ID: 2ed560bf0405
Revises: c40681f0afd9
Create Date: 2024-09-07 10:46:08.964047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed560bf0405'
down_revision: Union[str, None] = 'c40681f0afd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('id_user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'id_user')
    # ### end Alembic commands ###
