"""Fix games

Revision ID: 5162354d6676
Revises: a50f55ff820d
Create Date: 2024-08-27 19:38:32.073264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5162354d6676'
down_revision: Union[str, None] = 'a50f55ff820d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'id_pl_win',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'id_pl_win',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
