"""Create games

Revision ID: a50f55ff820d
Revises: 390d74084845
Create Date: 2024-08-26 19:31:07.757922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50f55ff820d'
down_revision: Union[str, None] = '390d74084845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pl1', sa.Integer(), nullable=False),
    sa.Column('id_pl2', sa.Integer(), nullable=False),
    sa.Column('pl1_1_1', sa.Integer(), nullable=False),
    sa.Column('pl1_1_2', sa.Integer(), nullable=False),
    sa.Column('pl1_1_3', sa.Integer(), nullable=False),
    sa.Column('pl1_2_1', sa.Integer(), nullable=False),
    sa.Column('pl1_2_2', sa.Integer(), nullable=False),
    sa.Column('pl1_2_3', sa.Integer(), nullable=False),
    sa.Column('pl1_3_1', sa.Integer(), nullable=False),
    sa.Column('pl1_3_2', sa.Integer(), nullable=False),
    sa.Column('pl1_3_3', sa.Integer(), nullable=False),
    sa.Column('pl1_1', sa.Integer(), nullable=False),
    sa.Column('pl1_2', sa.Integer(), nullable=False),
    sa.Column('pl1_3', sa.Integer(), nullable=False),
    sa.Column('pl1_count', sa.Integer(), nullable=False),
    sa.Column('pl2_1_1', sa.Integer(), nullable=False),
    sa.Column('pl2_1_2', sa.Integer(), nullable=False),
    sa.Column('pl2_1_3', sa.Integer(), nullable=False),
    sa.Column('pl2_2_1', sa.Integer(), nullable=False),
    sa.Column('pl2_2_2', sa.Integer(), nullable=False),
    sa.Column('pl2_2_3', sa.Integer(), nullable=False),
    sa.Column('pl2_3_1', sa.Integer(), nullable=False),
    sa.Column('pl2_3_2', sa.Integer(), nullable=False),
    sa.Column('pl2_3_3', sa.Integer(), nullable=False),
    sa.Column('pl2_1', sa.Integer(), nullable=False),
    sa.Column('pl2_2', sa.Integer(), nullable=False),
    sa.Column('pl2_3', sa.Integer(), nullable=False),
    sa.Column('pl2_count', sa.Integer(), nullable=False),
    sa.Column('status_games', sa.String(), nullable=False),
    sa.Column('id_pl_win', sa.Integer(), nullable=False),
    sa.Column('id_pl_move', sa.Integer(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pl1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_pl2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
