"""Fix

Revision ID: c40681f0afd9
Revises: 582f3dc86424
Create Date: 2024-09-06 23:06:59.586316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40681f0afd9'
down_revision: Union[str, None] = '582f3dc86424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_id_inventory_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'id_inventory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_id_inventory_fkey', 'user', 'inventory', ['id_inventory'], ['id'])
    # ### end Alembic commands ###
